### ISSUE TITLE
[question] I2C Device Table Entry. Type: 0xa0

### ISSUE THREAD

**Issue by karolherbst** [Gnurou/nouveau#12]
ftp://download.nvidia.com/open-gpu-doc/DCB/2/DCB-4.x-Specification.html

there is no type 0xa0 and we have a vbios with it (nvce gpu). Any clue what this is or is this just garbage data?

**Comment by Gnurou** [comment]
Hi,

Just looked it up and it appears this type is for internal use (and obsolete), which would explain why its documentation has been filtered out for the public release. You can just ignore it.

**Comment by karolherbst** [comment]
thanks for the answer :)
