### ISSUE TITLE
[question] nvbios: mapping of extedvs with 0x28 P table

### ISSUE THREAD

**Issue by karolherbst** [Gnurou/nouveau#8]
This should apply to all fermi+ cards

currently nvbios parses the tables like this (where everything in the SENSE table could be wrong):

the EXTDEV table is documented in ftp://download.nvidia.com/open-gpu-doc/DCB/2/DCB-4.x-Specification.html "I2C Device Table Entry"

```
EXTDEV table at 0x5602 version 4.0 unk04 0x00
EXTDEV 0: type 0x4e [INA3221] at 0x80 defbus 0 unk02_5 2 unk03 0x02
EXTDEV 1: type 0x4c [INA219] at 0x90 defbus 0 unk02_5 2 unk03 0x02
EXTDEV 2: type 0x4c [INA219] at 0x92 defbus 0 unk02_5 2 unk03 0x02

SENSE table at 0x7ed5, version 20
power rail 0: extdev_id/power_rail = 1, shunt resistor = 2 mOhm
power rail 1: extdev_id/power_rail = 2, shunt resistor = 2 mOhm
power rail 2: extdev_id/power_rail = 3, shunt resistor = 5 mOhm
```

so now the question: how can we map the power rails to the extdevs so that we read the right data out for each sensor?

**Comment by karolherbst** [comment]
ohh I figured that one out myself already :)

**Comment by Gnurou** [comment]
Great! How do you do then? :)

**Comment by karolherbst** [comment]
well on our Titan it doesn't work anymore as I thought it would be :D guess I closed that too fast. But I think I will manage anyway, because it wasn't wrong what I found out, it isn't just completly right
