### ISSUE TITLE
[question] What is EVO method 0x100 on base channel?

### ISSUE THREAD

**Issue by pierremoreau** [Gnurou/nouveau#9]
This method is not referenced in any of the released EVO headers (ftp://download.nvidia.com/open-gpu-doc/Display-Class-Methods/1/), but appeared in some traces and is apparently [set to `0xfffe0000` on page flip](https://github.com/envytools/envytools/blob/master/rnndb/display/nv_evo.xml#L947).

**Comment by Gnurou** [comment]
Not sure why this method has been filtered out but it seems to be on purpose. It doesn't look to be very important either, and the value it is set to should be fine for all cases. If you are ok with it I will leave it here for this one.
